include(Pch)

if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(GCC TRUE)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(CLANG TRUE)
endif()

if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(LINUX TRUE)
elseif (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(FREEBSD TRUE)
endif()

if (APPLE AND NOT IOS)
    set(MACOSX TRUE)
endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(X64 TRUE)
endif()

if (MSVC)
    include(directives/msvc)
elseif (GCC OR CLANG)
    include(directives/gcc)
else()
    message(FATAL_ERROR "Unsupported compiler ${CMAKE_CXX_COMPILER}. Please add the new compiler and try again")
endif()

if (WIN32 OR CYGWIN OR MINGW OR MSYS)
    include(directives/windows)
elseif(FREEBSD)
    include(directives/freebsd)
elseif(LINUX OR MACOSX)
    include(directives/unix)
else()
    message(FATAL_ERROR "Unsupported operative system ${CMAKE_SYSTEM_NAME}")
endif()
